# Generated by Django 4.2.7 on 2024-01-14 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commentary", "0003_alter_commentary_date_commentary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="date_commentary",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 14, 8, 6, 20, 651740)
            ),
        ),
    ]
