# Generated by Django 4.2.7 on 2024-01-14 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("commentary", "0007_alter_commentary_date_commentary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="date_commentary",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
