# Generated by Django 4.2.7 on 2024-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="post_image",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
