# Generated by Django 4.2.7 on 2023-12-21 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("follower", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follower",
            name="user",
        ),
        migrations.AddField(
            model_name="follower",
            name="follower_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_user",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="following_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_user",
                to="user.user",
            ),
        ),
    ]
