# Generated by Django 4.2.7 on 2023-12-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="user",
            field=models.ManyToManyField(blank=True, to="user.user"),
        ),
    ]
