# Generated by Django 4.2.7 on 2023-12-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("posts", "0002_posts_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="email",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="user",
        ),
        migrations.AddField(
            model_name="posts",
            name="user_id",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
            preserve_default=False,
        ),
    ]
