# Generated by Django 4.2.7 on 2023-12-12 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_posts_email_remove_posts_user_posts_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
