# Generated by Django 4.2.7 on 2023-12-13 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_posts_created_at_posts_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="user_id",
            new_name="user",
        ),
    ]
