# Generated by Django 4.2.7 on 2023-12-13 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_rename_user_id_posts_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="user",
            new_name="user_code",
        ),
    ]
