# Generated by Django 4.2.7 on 2023-12-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("posts", "0006_rename_user_posts_user_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="user_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
