# Generated by Django 4.2.7 on 2023-12-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("posts", "0010_alter_posts_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="user_name",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usernames",
                to="user.user",
            ),
        ),
    ]
