# Generated by Django 4.2.7 on 2023-12-15 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0009_alter_posts_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="user",
        ),
        migrations.AddField(
            model_name="posts",
            name="username",
            field=models.ForeignKey(
                default="xxx",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
            preserve_default=False,
        ),
    ]
