# Generated by Django 4.2.7 on 2024-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(blank=True, upload_to="img"),
        ),
    ]
