# Generated by Django 4.2.7 on 2024-01-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
